name: CI

on:
  push:

jobs:
  lint-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40

  test-service:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ["1.15", "1.16"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Unit Tests
        run: go test -v ./...
